

create database project_db;
use project_db;

create table testtbl(
 Customer_ID INT,
    Age INT,
    Gender VARCHAR(10),
    Item_Purchased VARCHAR(50),
    Category VARCHAR(50),
    Purchase_Amount_USD DECIMAL(10,2),
    Location VARCHAR(50),
    Size VARCHAR(10),
    Color VARCHAR(30),
    Season VARCHAR(20),
    Review_Rating DECIMAL(3,2),
    Subscription_Status VARCHAR(10),
    Payment_Method VARCHAR(30),
    Shipping_Type VARCHAR(30),
    Discount_Applied VARCHAR(10),
    Previous_Purchases INT,
    Preferred_Payment_Method VARCHAR(30),
    Frequency_of_Purchases VARCHAR(30)
);
show tables;
show databases;
use project_db;
select * from testtbl;
show tables;
select * from testtbl limit 10;



-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from testtbl
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from testtbl
where discount_applied ='yes' and purchase_amount >= (select avg(purchase_amount) from testtbl);

-- Q3. Which are the top 5 product with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from testtbl 
group by item_purchased
order  by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amount between Standard and Express Shipping.
select shipping_type,
round(avg(purchase_amount),2)
from testtbl
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do Subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from testtbl
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest purcentage of purchases withdiscounts applied?
select item_purchased,
round(sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from testtbl
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.


-- Q8. What are the top 3 most purcheased products within each category?
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Q10. What is the revenue contribution of each age group?




















